### ISSUE TITLE
dom EventListener on 'keyup' not working as expected

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/so-cards#19]
Attaching a `keyup` on form doesn't seem to work properly, as it is supposed to count letters on adding a key (+1) or deleting a key (-1)

https://github.com/bacloud14/so-cards/blob/3e5040bfad53a4870af16a2399ea8743a25bc5b8/main.js#L66

The _bug is that I can't figure out_ why on deleting one key sometimes number of characters counted are -1 but sometimes -2!

**Comment by IanFindlay** [comment]
Could this be due to encoding the string with the 'Codify' function prior to counting? I added a separate counter that counts the characters directly from 'formData.entries()' and it seems to keep an accurate count.

**Comment by bacloud14** [comment]
oh I'm sorry. I'm confusing things. The issue itself is not plausible.
In fact, it is not plain text (fields) that measured (for QR limitations); But the encoded one as a URL. 
So this explains why adding one character can add more or less characters to the URL.
I will revise this tomorrow because probably the issue has no place to be, and all is correct/.

**Comment by bacloud14** [comment]
Indeed 🤕  I need to revise the app hopefully there no visitors 😮 and this is so-c.me and not linktr.ee although this one doesn't keep peoples data 😄
