### ISSUE TITLE
[CSS] Better design

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/so-cards#6]
- Revise page layout
- Responsive
- Revise colors
- and so on 😮

**Comment by pattimcletchie** [comment]
@bacloud14 can you assign this to me? I would be more than happy to address the UI for you.

**Comment by bacloud14** [comment]
Sure @pattimcletchie 
I'm happy you are collaborating to this.

**Comment by pattimcletchie** [comment]
@bacloud14 thank you for assigning this! I will be working on this tonight (US, central timezone). If I run into any issues I will ping you.

I look forward to contributing.

**Comment by bacloud14** [comment]
Hello @pattimcletchie 
Please feel free, no time schedules .
Glad you can contribute to this!
Good luck 🤞

**Comment by pattimcletchie** [comment]
@bacloud14 working on it this evening. Sorry for the delay. Work got very busy.
