### ISSUE TITLE
Make input fields optional

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/so-cards#7]
If you go through code you understand quickly how I'm codifying input fields for different social media usernames. A user may have no YouTube for example. Making the field optional with a "greying" option and codifying that in URL (and QR code) seems useful. 
Should be version 4.

**Comment by SGI-CAPP-AT2** [comment]
Assign it to me !

**Comment by bacloud14** [comment]
The problem is not really in HTML, although what are you saying is write 👍 
I would like users to be able to "grey" somehow (maybe checkbox) fields, and also that would be codified in URL.
